--4. Crear un paquete que tenga una función, esta función retornará la cantidad de dietas almacenadas en la base de datos.
--Luego el paquete también debe contener una función que retorne la descripción de una dieta en específico, el código de la dieta se enviará como parámetro de la función.

CREATE OR REPLACE PACKAGE PK_FNEJ4

IS

 CANTIDAD_DIETAS NUMBER;
 DESCRIPCION_DIETA VARCHAR2(500);
 FUNCTION FN_CANTIDAD_DIETAS RETURN NUMBER;
 FUNCTION FN_DESCRIPCION_DIETA(DIETA_ID DIETA.DIETAID%TYPE) RETURN VARCHAR2;

END;

  CREATE OR REPLACE PACKAGE BODY PK_FNEJ4
  IS
   FUNCTION FN_CANTIDAD_DIETAS RETURN NUMBER
  IS 
   CANTIDAD_DIETAS NUMBER;
  BEGIN 
 
  SELECT COUNT(*) INTO CANTIDAD_DIETAS FROM dieta;
  RETURN CANTIDAD_DIETAS;
   END;
  
  FUNCTION FN_DESCRIPCION_DIETA(DIETA_ID DIETA.DIETAID%TYPE) RETURN VARCHAR2
  IS 
  DESCRIPCION_DIETA DIETA.DESCRIPCION%TYPE;
  BEGIN 
    SELECT DESCRIPCION INTO DESCRIPCION_DIETA FROM DIETA WHERE DIETAID = DIETA_ID; 
   
    RETURN DESCRIPCION_DIETA;
 
 END;
END;


----EJECUTAR---

SET SERVEROUTPUT ON;
 
DECLARE
 DESCRIPCION VARCHAR2(500);
 CANTIDAD_DIETAS NUMBER;
BEGIN
 DESCRIPCION:=PK_FNEJ4.FN_DESCRIPCION_DIETA(134134);
 CANTIDAD_DIETAS:=PK_FNEJ4.FN_CANTIDAD_DIETAS;
 DBMS_OUTPUT.PUT_LINE('LA CANTIDAD DE DIETAS ES:'||CANTIDAD_DIETAS);
 DBMS_OUTPUT.PUT_LINE('LA DESCRIPCION DE LA DIETA ES:'||DESCRIPCION);
END;