CREATE OR REPLACE PROCEDURE SP_INSERTA_TOMAS(hora TIMESTAMP, fecha date , 
animalId VARCHAR2, dietaId VARCHAR2, MSJ_ERROR OUT VARCHAR2, MSJ_EXITO OUT VARCHAR2)
IS
/*LLAVES FORANEAS: ANIMALID, DIETAID*/

/*DECLARAMOS VARIABLE*/
	VAL_MAX_TOMA_ID NUMBER;
  
BEGIN
/*CONTROLAMOS EL VALOR MAXIMO DE TOMAS*/
	SELECT (MAX(TOMAID)+1) INTO VAL_MAX_TOMA_ID FROM TOMAS;
  
  INSERT INTO TOMAS VALUES (VAL_MAX_TOMA_ID, hora, fecha, animalId, dietaId);
	COMMIT;

	MSJ_EXITO:='NUEVA TOMA EXITOSA';
  
/*BLOQUE DE EXCEPCIONES*/
	EXCEPTION
		WHEN OTHERS THEN
			MSJ_ERROR:=SQLERRM;
END;


DECLARE

/*CREAMOS VARIABLES PARA ERROR*/
	MSJ_ERROR VARCHAR2(500);
	MSJ_EXITO VARCHAR2(500);
BEGIN
/*LLAMAMOS AL PROCEDIMIENTO*/
  SP_INSERTA_TOMAS(TO_DATE('1999-10-08 18:48:00','YYYY-MM-DD HH24:MI:SS'),TO_DATE('1999-10-08','YYYY-MM-DD'),'G-12-AA','342567',MSJ_ERROR, MSJ_EXITO);
    DBMS_OUTPUT.PUT_LINE(MSJ_EXITO||' '||MSJ_ERROR);
END;

SET SERVEROUTPUT ON;



/*SABER CUAL ES EL VALOR MAXIMO DE TOMAS*/
SELECT MAX (TOMAID) FROM tomas;

/*SABER CUAL ES EL VALOR MAXIMO DE TOMAS +1*/
SELECT (MAX(tomaId)+1) FROM tomas;