--2. Crear una función que retorne los datos de todos los animales que se tienen 
--almacenados en la base de datos. .

CREATE OR REPLACE FUNCTION FN_ANIMALES
RETURN SYS_REFCURSOR
IS
	CDATOS SYS_REFCURSOR;
BEGIN
	OPEN CDATOS FOR SELECT * FROM ANIMALES;
	RETURN CDATOS;
END;



DECLARE
	DATOS_ANI SYS_REFCURSOR;
	REGISTRO ANIMALES%ROWTYPE;
	
BEGIN
	DATOS_ANI:=FN_ANIMALES;
	
	
	LOOP
		FETCH DATOS_ANI INTO REGISTRO;
		EXIT WHEN DATOS_ANI%NOTFOUND;
		DBMS_OUTPUT.PUT_LINE('EL ID DEL ANIMAL ES :'||REGISTRO.ANIMALID);
        DBMS_OUTPUT.PUT_LINE('LA ESPECIE DEL ANIMAL ES :'||REGISTRO.ESPECIE);
		DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL ES: '||REGISTRO.NOMBRE);
        DBMS_OUTPUT.PUT_LINE('EL PESO DEL ANIMAL ES :'||REGISTRO.PESO);
        DBMS_OUTPUT.PUT_LINE('LA FECHA DE NACIMIENTO DEL ANIMAL ES :'||REGISTRO.FECHANACIMIENTO);
        DBMS_OUTPUT.PUT_LINE('EL LUGAR DEL CODIGO ES :'||REGISTRO.LUGARCODIGO);
        DBMS_OUTPUT.PUT_LINE(CHR(13));
	END LOOP;

END;
