--3. Crear un procedimiento almacenado que llame a la función del inciso 2 y que se 
--encargue de imprimir toda la información que retorna la función.

CREATE OR REPLACE PROCEDURE SP_MOSTAR_ANIMALES
IS
  DATOS_ANIMALES SYS_REFCURSOR;
  
  TYPE FILA IS RECORD(
  ANIMALID ANIMALES.ANIMALID%TYPE,
  Especie ANIMALES.ESPECIE%TYPE,
  NOMBRE ANIMALES.NOMBRE%TYPE,
  PESO ANIMALES.PESO%TYPE,
  FECHA ANIMALES.FECHANACIMIENTO%TYPE,
  LUGAR ANIMALES.LUGARCODIGO%TYPE
  );
  
  REGISTRO FILA;
BEGIN
 DATOS_ANIMALES:=FN_ANIMALES;
  
  LOOP
     FETCH DATOS_ANIMALES INTO REGISTRO;
     EXIT WHEN DATOS_ANIMALES%NOTFOUND;
     DBMS_OUTPUT.PUT_LINE('ANIMALID: ' || REGISTRO.ANIMALID);
     DBMS_OUTPUT.PUT_LINE('ESPECIE: ' ||REGISTRO.ESPECIE);
     DBMS_OUTPUT.PUT_LINE('NOMBRE: ' ||REGISTRO.NOMBRE);
     DBMS_OUTPUT.PUT_LINE('PESO ' ||REGISTRO.PESO);
     DBMS_OUTPUT.PUT_LINE('FECHA: ' ||REGISTRO.FECHA);
     DBMS_OUTPUT.PUT_LINE('LUGAR: ' ||REGISTRO.LUGAR);
    DBMS_OUTPUT.PUT_LINE(CHR(13));
  END LOOP;
END;

 execute SP_MOSTAR_ANIMALES;


