/*2) Hacer uso de un BULK COLLECT mediante un bloque anónimo, el BULK COLLECT
debe obtener los datos de todos los clientes que tienen registradas órdenes.
Posteriormente se deben de imprimir los campos de id de cliente, nombre de cliente y
dirección del cliente. Se debe gestionar cualquier error que se pueda producir y mostrar
solamente un mensaje indicando el error que ha sucedido (valor 10%)
*/
DECLARE
  TYPE REGISTROS IS RECORD(
  COD_CLIENTE CUSTOMERS.CUSTOMER_ID%TYPE,
  NOMBRE_CLIENTE CUSTOMERS.NAME%TYPE,
  UBICACION CUSTOMERS.ADDRESS%TYPE
  );
  TYPE TABLA_CLIENTES IS TABLE OF REGISTROS INDEX BY PLS_INTEGER;
  DATOS_CLIENTES TABLA_CLIENTES;
  ITERACION NUMBER(10) :=0 ;
  
BEGIN 
  SELECT CUSTOMERS.CUSTOMER_ID, CUSTOMERS.NAME,CUSTOMERS.ADDRESS BULK COLLECT INTO DATOS_CLIENTES
    FROM CUSTOMERS 
    WHERE CUSTOMERS.CUSTOMER_ID IN (SELECT ORDERS.CUSTOMER_ID FROM ORDERS);
    
  WHILE(ITERACION<SQL%ROWCOUNT) LOOP
   DBMS_OUTPUT.PUT_LINE('EL CODIGO DEL CLIENTE ES: '||DATOS_CLIENTES(ITERACION+1).COD_CLIENTE);
        DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL CLIENTE ES: '||DATOS_CLIENTES(ITERACION+1).NOMBRE_CLIENTE);
        DBMS_OUTPUT.PUT_LINE('LA DIRECCION DEL CLIENTE ES: '||DATOS_CLIENTES(ITERACION+1).UBICACION);
        DBMS_OUTPUT.PUT_LINE(CHR(13));
    ITERACION := ITERACION + 1;
  END LOOP;
END;

  
    