/*4) Se pide crear una solución que permita ir registrando las acciones que se realizan en la
tabla COUNTRIES, es decir, cada vez que se realice una inserción, una modificación o
una eliminación en la tabla se debe almacenar cuáles eran los valores antiguos y cuáles
son los valores nuevos, según corresponda. Usted debe de crear toda la estructura
necesaria para que la solución funcione perfectamente. Es importante recordar que los
cambios se deben aprobar y en caso de error se deben deshacer todos los cambios
realizados. Se deben entregar todos los comandos de prueba necesarios para este
ejercicio. (valor 20%)*/

CREATE TABLE BITACORAS(
    PK_COD_BITACORA NUMBER PRIMARY KEY,
    DESCRIPCION VARCHAR2(2000),
    FECHA_HORA TIMESTAMP,
    USUARIO VARCHAR2(100),
    OPERACION VARCHAR2(50)
);

--CREACION DE LLAVE INCREMENTAL
CREATE SEQUENCE SQ_BITACORAS_20181002925
START WITH 1
INCREMENT BY 1;

--CREACION DEL TRIGGER
CREATE OR REPLACE TRIGGER TG_COUNTRIES_20181002925
AFTER INSERT OR UPDATE OR DELETE ON COUNTRIES
FOR EACH ROW

DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    IF (INSERTING) THEN
        INSERT INTO BITACORAS VALUES(SQ_BITACORAS_20181002925.NEXTVAL, 'SE REALIZO UN INSERT'||:NEW.COUNTRY_ID,
        SYSTIMESTAMP, USER, 'OPERACION INSERT');   
    END IF;

    IF(UPDATING) THEN
        INSERT INTO BITACORAS VALUES(SQ_BITACORAS_20181002925.NEXTVAL, 'SE REALIZO UN UPDATE EN LA TABLA COUNTRIES, EL 
        ANTERIOR: COUNTRY_ID: '||:OLD.COUNTRY_ID|| ' EL NUEVO COUNTRY_ID ES: '||:NEW.COUNTRY_ID||
        ' NOMBRE ANTERIOR DEL COUNTRY ERA: '||:OLD.COUNTRY_NAME||' NUEVO NOMBRE ES: '||
        :NEW.COUNTRY_NAME||' EL VALOR REGION ID ANTIGUO ERA : '||:OLD.REGION_ID||' NUEVA REGION: '||:NEW.REGION_ID,
        SYSTIMESTAMP, USER, 'OPERACION UPDATE'); 
    END IF;
    
    IF (DELETING) THEN
        INSERT INTO BITACORAS VALUES(SQ_BITACORAS_20181002925.NEXTVAL, 'SE REALIZO UN DELETE EN LA TABLA COUNTRIES, EL 
        COUNTRY ID ERA: '||:OLD.COUNTRY_ID||'  EL NOMBRE ERA: '||:OLD.COUNTRY_NAME,
        SYSTIMESTAMP, USER, 'OPERACION DELETE'); 
    END IF;

    COMMIT;
    
    EXCEPTION
        WHEN OTHERS THEN
        ROLLBACK;
  
END;


--PROBANDO UN INSERT
BEGIN
    INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME,REGION_ID)VALUES ('HN','HONDURASS', 1);
    commit;

END;


--PROBANDO EL UPDATE
BEGIN
    UPDATE COUNTRIES SET COUNTRY_NAME='HONDURAS' WHERE COUNTRY_NAME='HONDURASS';
    COMMIT;
    
END;

--PROBANDO EL TRIGGER CON UN DELETE
BEGIN
    DELETE  FROM COUNTRIES WHERE COUNTRY_NAME='HONDURAS';
    COMMIT;
    
END;





