DECLARE
  CURSOR CDATOS_PRODUCTO IS SELECT PRODUCTS.PRODUCT_ID,PRODUCTS.PRODUCT_NAME,PRODUCTS.DESCRIPTION,
  PRODUCTS.STANDARD_COST,PRODUCTS.LIST_PRICE,PRODUCTS.CATEGORY_ID,PRODUCT_CATEGORIES.CATEGORY_NAME,(LIST_PRICE - STANDARD_COST) GANANCIA FROM PRODUCTS
  INNER JOIN PRODUCT_CATEGORIES ON PRODUCTS.CATEGORY_ID = PRODUCT_CATEGORIES.CATEGORY_ID WHERE PRODUCT_CATEGORIES.CATEGORY_NAME='Storage';
  REGISTRO CDATOS_PRODUCTO%ROWTYPE;
BEGIN

 
  DBMS_OUTPUT.PUT_LINE('LA CANTIDAD DE REGISTROS ES: '||sql%ROWCOUNT);
  DBMS_OUTPUT.PUT_LINE(CHR(13)); 
 
 OPEN  CDATOS_PRODUCTO;
 
 LOOP
  FETCH CDATOS_PRODUCTO INTO REGISTRO;
  
  EXIT WHEN CDATOS_PRODUCTO%NOTFOUND;
  DBMS_OUTPUT.PUT_LINE('EL CODIGO DEL PRODUCTO ES: '||REGISTRO.PRODUCT_ID);
  DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL PRODUCTO ES: '||REGISTRO.PRODUCT_NAME);
  DBMS_OUTPUT.PUT_LINE('LA DESCRIPCION DEL PRODUCTO ES: '||REGISTRO.DESCRIPTION);
  DBMS_OUTPUT.PUT_LINE('EL COSTO ESTANDAR DEL PRODUCTO ES '||REGISTRO.STANDARD_COST);
  DBMS_OUTPUT.PUT_LINE('EL PRECIO DE VENTA DEL PRODUCTO ES '||REGISTRO.LIST_PRICE);
  DBMS_OUTPUT.PUT_LINE('LA GANANCIA DEL PRODUCTO ES '||REGISTRO.GANANCIA);
  DBMS_OUTPUT.PUT_LINE(CHR(13)); 
 END LOOP;
 CLOSE CDATOS_PRODUCTO;
    
 EXCEPTION 
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('EL CODIGO DEL ERROR ES :'||SQLCODE);
        DBMS_OUTPUT.PUT_LINE('EL MENSAJE DEL ERROR ES :'||SQLERRM);
    ROLLBACK;
END;

