CREATE USER BD_OT IDENTIFIED BY 123
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

CREATE ROLE ADMIN_OT;


GRANT CREATE SESSION, CREATE ANY TABLE ,CREATE ANY PROCEDURE ,CREATE ANY SEQUENCE, CREATE ANY TRIGGER, 
ALTER ANY TABLE, ALTER ANY PROCEDURE,ALTER ANY TRIGGER, ALTER ANY SEQUENCE,
DROP ANY TABLE, DROP  ANY PROCEDURE, DROP ANY SEQUENCE, DROP ANY TRIGGER TO ADMIN_OT;

GRANT ADMIN_OT TO BD_OT;