CREATE OR REPLACE PROCEDURE SP_INSERTA_PRODUCTO(NOMB_PROD VARCHAR,ID_BRAND  IN  NUMBER , CAT_ID NUMBER,
                                                ANIO_MODELO NUMBER, PRECIO NUMBER, NOMBRE_BRAND VARCHAR2,  MSJ_ERROR OUT VARCHAR2,
                                                MSJ_EXITO OUT VARCHAR2)
IS                               
    CANTIDAD_REGISTROS NUMBER;
    COD_BRAND NUMBER;
BEGIN

---SABER SI EXISTE EL VALOR O NO
    SELECT COUNT(*) INTO CANTIDAD_REGISTROS FROM BRANDS WHERE BRAND_ID = ID_BRAND; 
    
    
    IF (CANTIDAD_REGISTROS=1) THEN 
    ----Realizar el insert dentro de la tabla
        INSERT INTO PRODUCTS (PRODUCT_NAME, BRAND_ID, CATEGORY_ID, MODEL_YEAR, 
        LIST_PRICE) VALUES  (NOMB_PROD, ID_BRAND, CAT_ID , ANIO_MODELO, PRECIO);
    ----HACER COMMIT SI LA INSERCION SE AGREGO DE LA FORMA CORRECTA
        COMMIT;
    ---PARA SABER SI SE EJECEUTO DE FOMA EXITOSA
        MSJ_EXITO:='LA INSERCION DEL PRODUCTO FUE EXITOSA';
    
    ELSE 
        SP_INSERTA_BRAND(NOMBRE_BRAND, COD_BRAND);
        INSERT INTO PRODUCTS (PRODUCT_NAME, BRAND_ID, CATEGORY_ID, MODEL_YEAR, 
        LIST_PRICE) VALUES  (NOMB_PROD,COD_BRAND, CAT_ID , ANIO_MODELO, PRECIO);
        ----HACER COMMIT SI LA INSERCION SE AGREGO DE LA FORMA CORRECTA
        COMMIT;
    ---PARA SABER SI SE EJECEUTO DE FOMA EXITOSA
        MSJ_EXITO:='LA INSERCION DEL PRODUCTO FUE EXITOSA';
    
     END IF;
    
------CONTROLOAR ERRORES DE LINEA 10 A TRAVES DE EXCEPCIONES
    EXCEPTION 
        WHEN OTHERS THEN 
            MSJ_ERROR:=SQLERRM;
            
END;


DECLARE 
    MSJ_ERROR VARCHAR2(500);
    MSJ_EXITO VARCHAR(500);

BEGIN
    SP_INSERTA_PRODUCTO('BICICLETA DE PRUEBA 1', 30,3,2018,4345, 'BRAND_PRUEBA',MSJ_ERROR, MSJ_EXITO);
    DBMS_OUTPUT.PUT_LINE(MSJ_EXITO||' '||MSJ_ERROR);

END;

SET SERVEROUTPUT ON


