CREATE OR REPLACE PROCEDURE SP_INSERTA_PRODUCTO(NOMB_PROD VARCHAR,ID_BRAND NUMBER, CAT_ID NUMBER, 
                                                ANIO_MODELO NUMBER, PRECIO NUMBER, MSJ_ERROR OUT VARCHAR2,
                                                MSJ_EXITO OUT VARCHAR2)
IS
    VAL_MAX_PROD_ID NUMBER;                                        
                                                
BEGIN
---CONTROLAR CUAL ES EL VALOR MAXIMO 
    SELECT (MAX(PRODUCT_ID)+1) INTO VAL_MAX_PROD_ID FROM PRODUCTS;
----Realizar el insert dentro de la tabla
    INSERT INTO PRODUCTS VALUES(VAL_MAX_PROD_ID, NOMB_PROD, ID_BRAND, CAT_ID , ANIO_MODELO, PRECIO);
-----HACER COMMIT SI LA INSERCION SE AGREGO DE LA FORMA CORRECTA
    COMMIT;
---PARA SABER SI SE EJECEUTO DE FOMA EXITOSA
    MSJ_EXITO:='LA INSERCION DEL PRODUCTO FUE EXITOSA';

------CONTROLOAR ERRORES DE LINEA 10 A TRAVES DE EXCEPCIONES
    EXCEPTION 
        WHEN OTHERS THEN 
            MSJ_ERROR:=SQLERRM;
            
END;


DECLARE 
    MSJ_ERROR VARCHAR2(500);
    MSJ_EXITO VARCHAR(500);

BEGIN
    SP_INSERTA_PRODUCTO('BICICLETA DE MONTAÒA', 1,20,2019,4345, MSJ_ERROR, MSJ_EXITO);
    DBMS_OUTPUT.PUT_LINE(MSJ_EXITO||' '||MSJ_ERROR);

END;

SET SERVEROUTPUT ON


SELECT (MAX(PRODUCT_ID)+1)  FROM PRODUCTS; --Obteniendo el siguiente valor