SELECT * FROM PRODUCTS WHERE PRODUCT_NAME ='BICICLETA DE PRUEBA 1';


CREATE SEQUENCE SQ_PRODUCTS
START WITH 323
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SQ_PRODUCTS
BEFORE INSERT ON PRODUCTS
FOR EACH ROW

DECLARE

BEGIN
    :NEW.PRODUCT_ID:=SQ_PRODUCTS.NEXTVAL;
END;

