CREATE OR REPLACE PROCEDURE SP_CANT_PRODUCTOS

IS
    CANTIDAD NUMBER;
BEGIN
    SELECT COUNT(*) INTO CANTIDAD FROM PRODUCTS;
    DBMS_OUTPUT.PUT_LINE('LA CANTIDAD DE PRODUCTOS GUARDADOS ES: '||CANTIDAD);
END;

---Para ejecutar
EXECUTE SP_CANT_PRODUCTOS;

SET SERVEROUTPUT ON