DECLARE
    CURSOR CDATOS_ORDENES IS SELECT ORDENES.DESCUENTO AS DESCU, ORDENES.ORDENID FROM ORDENES;
    DESCUENTO CDATOS_ORDENES%ROWTYPE;
    VALOR NUMBER:=0;
BEGIN
    OPEN CDATOS_ORDENES;
    
    LOOP 
        FETCH CDATOS_ORDENES INTO DESCUENTO;
        
        EXIT WHEN CDATOS_ORDENES%NOTFOUND;
        
        IF(DESCUENTO.DESCU IS NULL) THEN
            VALOR:=1;
            UPDATE ORDENES SET ORDENES.DESCUENTO = 15 WHERE DESCUENTO.ORDENID = ORDENES.ORDENID;
            COMMIT;
        END IF;
    END LOOP;
    
    IF VALOR=0 THEN
        DBMS_OUTPUT.PUT_LINE('REGISTROS NO ENCONTRADOS');
    END IF;
   CLOSE CDATOS_ORDENES;
END;