/*TRIGGER PARA TABLA CATEGORIAS*/
CREATE OR REPLACE TRIGGER TG_INSERT_CATEGORIAS
BEFORE INSERT ON CATEGORIAS
FOR EACH ROW
DECLARE
BEGIN
    :NEW.NOMBRECAT:=LOWER(:NEW.NOMBRECAT);

END;

INSERT INTO CATEGORIAS VALUES (701, 'COMIDA RAPIDA');