CREATE OR REPLACE TRIGGER TG_INSERTA_CLIENTES
BEFORE INSERT ON CLIENTES
FOR EACH ROW
BEGIN

    :NEW.CEDULA_RUC:=LOWER(:NEW.CEDULA_RUC);
    :NEW.NOMBRECIA:=LOWER(:NEW.NOMBRECIA);
    :NEW.NOMBRECONTACTO:=LOWER(:NEW.NOMBRECONTACTO);
    :NEW.DIRECCIONCLI:=LOWER(:NEW.DIRECCIONCLI);
    :NEW.FAX:=LOWER(:NEW.FAX);
    :NEW.EMAIL:=LOWER(:NEW.EMAIL);
    :NEW.CELULAR:=LOWER(:NEW.CELULAR);
    :NEW.FIJO:=LOWER(:NEW.FIJO);

END;

--TRIGGER PARA TABLA CATEGORIAS
CREATE OR REPLACE TRIGGER TG_INSERTA_CATEGORIAS
BEFORE INSERT ON CATEGORIAS
FOR EACH ROW
DECLARE


BEGIN
 :NEW.NOMBRECAT:=LOWER(:NEW.NOMBRECAT);
 
END;


INSERT  INTO CLIENTES VALUES (12,'08012000','HERMANOS','JUAN MAYEN','DOLORES','IHIUGU','JM@GMAIL.COM','996583','227081');
INSERT  INTO CLIENTES VALUES (13,'07012000','OLIMPO','MARIA','LA SOSA',null,null,null,null);
INSERT INTO CATEGORIAS VALUES (800, 'PANTALONES');
