CREATE USER BD_PEDIDOS IDENTIFIED BY 123
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

CREATE ROLE ADMIN_PEDIDOS;

GRANT CREATE SESSION, CREATE ANY TABLE,CREATE ANY PROCEDURE, ALTER ANY TABLE, ALTER ANY PROCEDURE,
DROP ANY TABLE, DROP  ANY PROCEDURE TO ADMIN_PEDIDOS;


GRANT ADMIN_PEDIDOS TO BD_PEDIDOS;

SELECT * FROM DBA_ROLES;

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'ADMIN';