CREATE USER BD_SegundoExamen IDENTIFIED BY 123
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

CREATE ROLE ADMIN_Segundo_Examen;


GRANT CREATE SESSION, CREATE ANY TABLE ,CREATE ANY PROCEDURE ,CREATE ANY SEQUENCE, CREATE ANY TRIGGER, 
ALTER ANY TABLE, ALTER ANY PROCEDURE,ALTER ANY TRIGGER, ALTER ANY SEQUENCE,
DROP ANY TABLE, DROP  ANY PROCEDURE, DROP ANY SEQUENCE, DROP ANY TRIGGER TO ADMIN_Segundo_Examen;

GRANT ADMIN_Segundo_Examen TO BD_SegundoExamen;


GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY PROCEDURE, CREATE ANY TRIGGER, CREATE ANY SEQUENCE, CREATE ANY JOB, 
ALTER ANY TABLE, ALTER ANY PROCEDURE, ALTER ANY TRIGGER, ALTER ANY SEQUENCE, 
DROP ANY TABLE, DROP ANY PROCEDURE, DROP ANY TRIGGER, DROP ANY SEQUENCE TO BD_PAGOS; 