

create database  DW_PAGO_Tarea2;

USE DW_PAGO_Tarea2;

CREATE TABLE DEPARTAMENTO(
ID_DEPARTAMENTO INT PRIMARY KEY,
DEPARTAMENTO VARCHAR (50)
)
;

CREATE TABLE CLIENTE(
ID_CLIENTE INT PRIMARY KEY,
NOMBRE VARCHAR (100)

)
;


CREATE TABLE TIEMPO(
ID_TIEMPO DATE NOT NULL PRIMARY KEY,
AÑO INT,
SEMESTRE INT,
NUM_MES INT, 
TRIMESTRE INT,
DIA_NOMBRE VARCHAR (20),
)
;

CREATE TABLE EMPLEADO(
ID_EMPLEADO INT PRIMARY KEY,
NOMBRE VARCHAR (100)

)
;

CREATE TABLE HECHOSPAGOS(
ID_REGISTRO INT PRIMARY KEY IDENTITY (1,1),
ID_DEPARTAMENTO INT FOREIGN KEY REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO) NOT NULL,
ID_CLIENTE INT FOREIGN KEY REFERENCES CLIENTE(ID_CLIENTE) NOT NULL,
ID_TIEMPO DATE FOREIGN KEY REFERENCES TIEMPO(ID_TIEMPO) NOT NULL,
ID_EMPLEADO INT FOREIGN KEY REFERENCES EMPLEADO(ID_EMPLEADO) NOT NULL,
CONTEO_PAGOS_MES INT,
TOTAL_MONTO_MES DECIMAL (10,2)
)
;