
-------PARA LA TABLA DEPARTAMENTOS-------
SELECT id_departamento , departamento FROM departamento

--------PARA LA TABLA CLIENTE----
SELECT id_cliente , CONCAT(nombre , ' ' , apellido) nombre FROM cliente

---------PARA LA TABLA EMPLEADO----
SELECT id_empleado , CONCAT(nombre, ' ' , apellido) nombre FROM empleado

-------PARA LA TABLA TIEMPO----

SELECT CONVERT(DATE, fecha_pago) tiempoId, DATEPART(YEAR, fecha_pago) año, 
DATEPART(MONTH, fecha_pago) mes, DATEPART(dayofyear , fecha_pago) dia_año, 
((DATEPART(quarter, FECHA_PAGO)-1)/2)+1 SEMESTRE,
DATEPART(QUARTER, fecha_pago) trimestre 
FROM PAGO
GROUP BY PAGO.FECHA_PAGO

----Para Hechos Pago------

SELECT PAGO.ID_EMPLEADO, DEPARTAMENTO.ID_DEPARTAMENTO,PAGO.ID_CLIENTE,CONVERT(DATE, FECHA_PAGO) "Mes", 
COUNT(ID_PAGO) OVER (PARTITION BY DATEPART(MONTH, FECHA_PAGO), DATEPART(YEAR, FECHA_PAGO)) "Cantidad de pagos en el mes", 
SUM(MONTO) OVER (PARTITION BY DATEPART(MONTH, FECHA_PAGO), DATEPART(YEAR, FECHA_PAGO)) "Monto de pagos del mes" FROM PAGO
INNER JOIN EMPLEADO ON EMPLEADO.ID_EMPLEADO = PAGO.ID_EMPLEADO
INNER JOIN DIRECCION ON DIRECCION.ID_DIRECCION = EMPLEADO.ID_DIRECCION
INNER JOIN CIUDAD ON CIUDAD.ID_CIUDAD = DIRECCION.ID_CIUDAD
INNER JOIN DEPARTAMENTO ON CIUDAD.ID_DEPARTAMENTO = DEPARTAMENTO.ID_DEPARTAMENTO
INNER JOIN CLIENTE ON CLIENTE.ID_CLIENTE = PAGO.ID_CLIENTE
GROUP BY PAGO.ID_EMPLEADO, PAGO.ID_CLIENTE, DEPARTAMENTO.ID_DEPARTAMENTO, FECHA_PAGO, MONTO, ID_PAGO
ORDER BY SUM(MONTO) OVER (PARTITION BY DATEPART(MONTH, FECHA_PAGO), DATEPART(YEAR, FECHA_PAGO)) DESC;
