

CREATE OR REPLACE FUNCTION FN_DATOS_TIENDA(ID_TIENDA STORES.STORE_ID%TYPE, TELEFONO OUT STORES.PHONE%TYPE,
CORREO OUT STORES.EMAIL%TYPE, DIRECCION OUT STORES.STREET%TYPE)
RETURN VARCHAR2

IS 
    NOMBRE_TIENDA STORES.STORE_NAME%TYPE;

BEGIN

    SELECT STORE_NAME , PHONE, EMAIL , STREET INTO NOMBRE_TIENDA, TELEFONO , CORREO ,DIRECCION FROM STORES WHERE
    STORE_ID =ID_TIENDA;

    RETURN NOMBRE_TIENDA;

END;
  
DECLARE
    NOMBRE_TIENDA STORES.STORE_NAME%TYPE;
    TELEFONO  stores.phone%TYPE;
    CORREO STORES.EMAIL%TYPE;
    DIRECCION  STORES.STREET%TYPE;

BEGIN
    NOMBRE_TIENDA:=FN_DATOS_TIENDA (2, TELEFONO ,CORREO , DIRECCION );
    DBMS_OUTPUT.PUT_LINE('EL NOMBRE DE LA TIENDA ES: '||NOMBRE_TIENDA);
    DBMS_OUTPUT.PUT_LINE('EL TELEFONO DE LA TIENDA ES: '||TELEFONO);
    DBMS_OUTPUT.PUT_LINE('EL CORREO DE LA TIENDA ES: '||CORREO);
    DBMS_OUTPUT.PUT_LINE('LA DIRECCION DE LA TIENDA ES: '||DIRECCION);
END;

  
  set SERVEROUTPUT on;