DECLARE
    NOMBRE VARCHAR2(500);

BEGIN
    NOMBRE := PK_INF_VENTA_BICICLETAS.FN_NOMBRE_TIENDA(2);
    DBMS_OUTPUT.PUT_LINE('EL NOMBRE ED LA TIENDA ES: '||NOMBRE);
    PK_INF_VENTA_BICICLETAS.SP_INSERTA_BRAND ('LADY LEE');
END;



