--CREACION DE SEQUENCIA
CREATE SEQUENCE SQ_TABLA_DESTINO
START WITH 17
INCREMENT BY 1
MINVALUE 17
MAXVALUE 999;

--CREACION DE TRIGGER
CREATE OR REPLACE TRIGGER TG_SQ_TABLA_DESTINO
BEFORE INSERT ON DESTINO
FOR EACH ROW

DECLARE
    
BEGIN
    :new.cod_destino := ('DESTINO-N'||SQ_TABLA_DESTINO.NEXTVAL);
END;


BEGIN
    INSERT INTO DESTINO(nombre_destino, CIUDAD_DESTINO, DESC_DESTINO) values ('HDFR','DERGE','GRE')  ;
END;




