DECLARE
    TYPE FILA IS RECORD(
        NIF_EMPRESA TRASLADO.NIF_EMPRESA%TYPE,
        COD_RESIDUO TRASLADO.COD_RESIDUO%TYPE,
        FECHA_ENVIO TRASLADO.FECHA_ENVIO%TYPE,
        COD_DESTINO TRASLADO.COD_DESTINO%TYPE,
        ENVASE TRASLADO.ENVASE%TYPE,
        FECHA_LLEGADA TRASLADO.FECHA_LLEGADA%TYPE,
        TRATAMIENTO TRASLADO.TRATAMIENTO%TYPE,
        CANTIDAD_TRASLADO TRASLADO.CANTIDAD_TRASLADO%TYPE,
        DESC_TRASLADO TRASLADO.DESC_TRASLADO%TYPE,
        DESC_RESIDUO RESIDUO.DESC_RESIDUO%TYPE,
        TOXICIDAD RESIDUO.TOXICIDAD%TYPE
    );
    
    TYPE TABLA_TRASLADO IS TABLE OF FILA INDEX BY PLS_INTEGER;
    DATOS_TRASLADO TABLA_TRASLADO;
    ITERACION NUMBER(10):=0;
    
    
BEGIN

    SELECT TRASLADO.NIF_EMPRESA,TRASLADO.COD_RESIDUO,TRASLADO.FECHA_ENVIO,
    TRASLADO.COD_DESTINO, TRASLADO.ENVASE, TRASLADO.FECHA_LLEGADA,
    TRASLADO.TRATAMIENTO, TRASLADO.CANTIDAD_TRASLADO, TRASLADO.DESC_TRASLADO,
    RESIDUO.DESC_RESIDUO, RESIDUO.TOXICIDAD
    BULK COLLECT INTO DATOS_TRASLADO FROM TRASLADO 
    INNER JOIN RESIDUO ON traslado.cod_residuo = residuo.cod_residuo;
    DBMS_OUTPUT.PUT_LINE('LA CANTIDAD DE REGISTROS ES: '||SQL%ROWCOUNT);
    
   
    
    WHILE(ITERACION<SQL%ROWCOUNT)LOOP
        IF (MONTH(DATOS_TRASLADO(ITERACION+1).FECHA_ENVIO) =8) AND(DATOS_TRASLADO(ITERACION+1).TRATAMIENTO = 'Incineración' OR DATOS_TRASLADO(ITERACION+1).TRATAMIENTO ='Almacenamiento') THEN
            
            DBMS_OUTPUT.PUT_LINE('EL NIF_EMPRESA ES: '||DATOS_TRASLADO(ITERACION+1).NIF_EMPRESA);
            DBMS_OUTPUT.PUT_LINE('EL COD DE RESIDUO ES: '||DATOS_TRASLADO(ITERACION+1).COD_RESIDUO);
            DBMS_OUTPUT.PUT_LINE('LA FECHA DE ENVIO ES: '||DATOS_TRASLADO(ITERACION+1).FECHA_ENVIO);
            DBMS_OUTPUT.PUT_LINE('EL CODIGO DE DESTINO ES: '||DATOS_TRASLADO(ITERACION+1).COD_DESTINO);
            DBMS_OUTPUT.PUT_LINE('EL ENVASE ES: '||DATOS_TRASLADO(ITERACION+1).ENVASE);
            DBMS_OUTPUT.PUT_LINE('LA FECHA DE LLEGADA ES: '||DATOS_TRASLADO(ITERACION+1).FECHA_LLEGADA);
            DBMS_OUTPUT.PUT_LINE('EL TRATAMIENTO ES: '||DATOS_TRASLADO(ITERACION+1).TRATAMIENTO);
            DBMS_OUTPUT.PUT_LINE('LA CANTIDAD DE TRASLADO ES: '||DATOS_TRASLADO(ITERACION+1).CANTIDAD_TRASLADO);
            DBMS_OUTPUT.PUT_LINE('EL DESC_TRASLADO ES: '||DATOS_TRASLADO(ITERACION+1).DESC_TRASLADO);
            DBMS_OUTPUT.PUT_LINE('EL DESC_RESIDUO  ES: '||DATOS_TRASLADO(ITERACION+1).DESC_RESIDUO);
            DBMS_OUTPUT.PUT_LINE('LA TOXICIDAD ES: '||DATOS_TRASLADO(ITERACION+1).TOXICIDAD);
            DBMS_OUTPUT.PUT_LINE(CHR(13));
            
            ITERACION:=ITERACION+1;
            
        END IF;
     
    END LOOP;
 
END;


