--Crear un usuario con nombre analista y contraseña analist
CREATE USER ANALISTA IDENTIFIED BY analista
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

CREATE ROLE Administradoress;

GRANT CREATE SESSION, CREATE ANY TABLE ,CREATE ANY PROCEDURE ,CREATE ANY SEQUENCE, CREATE ANY TRIGGER, 
ALTER ANY TABLE, ALTER ANY PROCEDURE,ALTER ANY TRIGGER, ALTER ANY SEQUENCE,
DROP ANY TABLE, DROP  ANY PROCEDURE, DROP ANY SEQUENCE, DROP ANY TRIGGER TO administradoress;

GRANT ADMINISTRADORESS TO ANALISTA;

