CREATE USER BD_RESIDUOS_TOXICOS IDENTIFIED BY 123
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

CREATE ROLE ADMIN_RT;

GRANT CREATE SESSION, CREATE ANY TABLE ,CREATE ANY PROCEDURE ,CREATE ANY SEQUENCE, CREATE ANY TRIGGER, 
ALTER ANY TABLE, ALTER ANY PROCEDURE,ALTER ANY TRIGGER, ALTER ANY SEQUENCE,
DROP ANY TABLE, DROP  ANY PROCEDURE, DROP ANY SEQUENCE TO ADMIN_RT;

GRANT ADMIN_RT TO BD_RESIDUOS_TOXICOS;

